version: '3'
tasks:
  mtest-4:
    cmds:
      - ./metricstest -test.v -test.run=^TestIteration4$ -agent-binary-path=./cmd/agent/agent -binary-path=./cmd/server/server -server-port=8080 -source-path=./
  build-server:
    cmds:
      - go build -o cmd/server/server cmd/server/main.go
  build-agent:
    cmds:
      - go build -o cmd/agent/agent cmd/agent/main.go